### ISSUE TITLE
Update messaging for signing transactions

### ISSUE THREAD

**Issue by stellarmagnet** [spacedecentral/planning-suite#211]
Replace with: `Execute the result of range vote #1`

![image.png](https://images.zenhubusercontent.com/5ab2c6f24b5806bc2bcbd667/bf6efdff-8c70-40e0-a550-eb0e0582572e)

I feel like this needs to change but not sure what to - `Cast a range vote` ? @Quazia 
![image.png](https://images.zenhubusercontent.com/5ab2c6f24b5806bc2bcbd667/92146824-2f68-4439-ab92-c52e12f3c04e)

**Comment by ottodevs** [comment]
I don't feel this is a good informative message for the action to be triggered...
The action does not actually "allow something", it just Casts the vote, so for me that part is superfluous and can lead to confusion to the user, since "Allow" word has more a kind of permission meaning.

https://hack.aragon.org/docs/human-readable-txs.html

I am sure we can manage to create a more informative message with the options available, what do you think?

**Comment by Quazia** [comment]
Fixed in #244
